name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  version-bump:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install toml
      run: python -m pip install toml

    - name: Bump version
      run: |
        VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
        NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++; print}')
        sed -i "s/version = \"$VERSION\"/version = \"$NEW_VERSION\"/" pyproject.toml
        echo "Bumped version to $NEW_VERSION"
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -am "Bump version to $NEW_VERSION"
        git push


  release-build:
    runs-on: ubuntu-latest
    needs: version-bump

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

